In [49]:
import numpy as np
import pandas as pd
from ydata_profiling import ProfileReport

# Question 1

In [111]:
df = pd.read_csv('bankloan.csv')
df.describe()

,Row ID,id,member_id,loan_amnt,funded_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,...,mths_since_last_major_derog,annual_inc_joint,dti_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,Unnamed: 50,36months,60months
count,368.000000,2.129990e+05,2.129990e+05,212999.000000,212999.000000,212999.000000,212999.000000,2.129990e+05,212999.000000,212999.000000,...,62365.000000,441.000000,439.000000,212999.000000,212999.000000,2.129990e+05,2.129990e+05,0.0,511.000000,511.000000
mean,184.500000,6.103515e+07,6.515927e+07,15257.965530,15257.965530,12.401658,440.842921,7.780071e+04,19.360817,0.347462,...,45.468356,107574.096327,18.320114,0.005718,261.951652,1.416537e+05,3.444425e+04,NaN,0.622309,0.377691
std,106.376689,4.734904e+06,5.215173e+06,8611.713377,8611.713377,4.249365,245.858646,8.188065e+04,31.925871,0.921209,...,22.645675,47921.057382,7.230012,0.081045,2215.188372,1.568766e+05,3.531827e+04,NaN,0.485285,0.485285
min,1.000000,5.670500e+04,7.082500e+04,1000.000000,1000.000000,5.320000,30.120000,0.000000e+00,0.000000,0.000000,...,0.000000,17950.000000,3.050000,0.000000,0.000000,0.000000e+00,0.000000e+00,NaN,0.000000,0.000000
25%,92.750000,5.783411e+07,6.158651e+07,8500.000000,8500.000000,9.170000,262.230000,4.700000e+04,12.660000,0.000000,...,28.000000,75001.000000,13.185000,0.000000,0.000000,3.143300e+04,1.460000e+04,NaN,0.000000,0.000000
50%,184.500000,6.137900e+07,6.549753e+07,14000.000000,14000.000000,12.290000,382.870000,6.500000e+04,18.720000,0.000000,...,45.000000,100000.000000,17.750000,0.000000,0.000000,8.138600e+04,2.510000e+04,NaN,1.000000,0.000000
75%,276.250000,6.503778e+07,6.956436e+07,20000.000000,20000.000000,14.650000,578.790000,9.250000e+04,25.520000,0.000000,...,63.000000,131000.000000,22.650000,0.000000,0.000000,2.097080e+05,4.260000e+04,NaN,1.000000,1.000000
max,368.000000,6.861687e+07,7.351969e+07,35000.000000,35000.000000,28.990000,1445.460000,9.000000e+06,9999.000000,30.000000,...,171.000000,410000.000000,43.860000,5.000000,380757.000000,4.127799e+06,1.641300e+06,NaN,1.000000,1.000000

In [63]:
profile = ProfileReport(df)

In [36]:
profile.to_file('report.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/53 [00:00<?, ?it/s]
  2%|▏         | 1/53 [00:00<00:17,  3.05it/s]
  4%|▍         | 2/53 [00:01<00:37,  1.37it/s]
  6%|▌         | 3/53 [00:01<00:22,  2.25it/s]
  8%|▊         | 4/53 [00:01<00:16,  3.00it/s]
 51%|█████     | 27/53 [00:01<00:00, 32.90it/s]
 62%|██████▏   | 33/53 [00:02<00:00, 23.59it/s]
 72%|███████▏  | 38/53 [00:02<00:00, 25.30it/s]
 91%|█████████ | 48/53 [00:02<00:00, 33.15it/s]
100%|██████████| 53/53 [00:02<00:00, 19.66it/s]
/Users/thanasisxan/repos/AI-101-Machine-Learning/.venv/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/Users/thanasisxan/repos/AI-101-Machine-Learning/.venv/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/Users/thanasisxan/repos/AI-101-Machine-Learning/.venv/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/Users/thanasisxan/repos/AI-101-Machine-Learning/.venv/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/Users/thanasisxan/repos/AI-101-Machine-Learning/.venv/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

# Question 2

## 1.

* mean: 15257.966
* max: 35000
* min: 1000

## 2.

In [91]:
df.columns

Index(['Row ID', 'id', 'member_id', 'loan_amnt', 'funded_amnt', 'term',
       'int_rate', 'installment', 'grade', 'sub_grade', 'emp_title',
       'emp_length', 'home_ownership', 'annual_inc', 'verification_status',
       'issue_d', 'loan_status', 'purpose', 'title', 'dti', 'delinq_2yrs',
       'earliest_cr_line', 'inq_last_6mths', 'mths_since_last_delinq',
       'open_acc', 'pub_rec', 'revol_bal', 'revol_util', 'total_acc',
       'initial_list_status', 'out_prncp', 'total_pymnt', 'total_rec_prncp',
       'total_rec_int', 'total_rec_late_fee', 'recoveries',
       'collection_recovery_fee', 'last_pymnt_d', 'last_pymnt_amnt',
       'next_pymnt_d', 'last_credit_pull_d', 'collections_12_mths_ex_med',
       'mths_since_last_major_derog', 'application_type', 'annual_inc_joint',
       'dti_joint', 'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal',
       'total_rev_hi_lim', 'Unnamed: 50', '36months', '60months'],
      dtype='object')

Variables to drop for training:
* Row ID
* id
* member_id
* Unnamed: 50
* 36months
* 60months
* acc_now_delinq
* delinq_2yrs
* dti
* application_type
* collections_12_mths_ex_med
* collection_recovery_fee
* recoveries
* total_rec_late_fee
* issue_d
* loan_status
* emp_title
* desc
* addr_state
* zip_code
* earliest_cr_line
* mths_since_last_delinq
* dti_joint
* annual_inc_joint
* funded_amnt
* grade
* sub_grade

In [112]:
df.drop(columns=[
    'Row ID', 'id', 'member_id', 'Unnamed: 0', 'Unnamed: 50', 'url', 'desc', 'policy_code',
    '36months', '60months',
    'funded_amnt', 'funded_amnt_inv',
    'emp_title', 'title', 'zip_code', 'addr_state',
    'application_type',
    'dti_joint', 'annual_inc_joint', 'verification_status_joint',
    'issue_d', 'pymnt_plan',
    'loan_status',
    'out_prncp', 'out_prncp_inv',
    'total_pymnt', 'total_pymnt_inv',
    'total_rec_prncp', 'total_rec_int', 'total_rec_late_fee',
    'recoveries', 'collection_recovery_fee',
    'last_pymnt_d', 'last_pymnt_amnt',
    'next_pymnt_d', 'last_credit_pull_d',
    'grade', 'int_rate', 'installment'
], inplace=True, errors='ignore')

## 3.

In [95]:
df.isnull().mean()

loan_amnt                      0.000000
term                           0.000000
sub_grade                      0.000000
emp_length                     0.059939
home_ownership                 0.000000
annual_inc                     0.000000
verification_status            0.000000
purpose                        0.000000
dti                            0.000000
delinq_2yrs                    0.000000
earliest_cr_line               0.000000
inq_last_6mths                 0.000000
mths_since_last_delinq         0.485312
open_acc                       0.000000
pub_rec                        0.000000
revol_bal                      0.000000
revol_util                     0.000385
total_acc                      0.000000
initial_list_status            0.000000
collections_12_mths_ex_med     0.000000
mths_since_last_major_derog    0.707205
acc_now_delinq                 0.000000
tot_coll_amt                   0.000000
tot_cur_bal                    0.000000
total_rev_hi_lim               0.000000
36months                       0.997601
60months                       0.997601
dtype: float64

In [96]:
df.columns

Index(['loan_amnt', 'term', 'sub_grade', 'emp_length', 'home_ownership',
       'annual_inc', 'verification_status', 'purpose', 'dti', 'delinq_2yrs',
       'earliest_cr_line', 'inq_last_6mths', 'mths_since_last_delinq',
       'open_acc', 'pub_rec', 'revol_bal', 'revol_util', 'total_acc',
       'initial_list_status', 'collections_12_mths_ex_med',
       'mths_since_last_major_derog', 'acc_now_delinq', 'tot_coll_amt',
       'tot_cur_bal', 'total_rev_hi_lim', '36months', '60months'],
      dtype='object')

In [97]:
df.describe()

,loan_amnt,annual_inc,dti,delinq_2yrs,inq_last_6mths,mths_since_last_delinq,open_acc,pub_rec,revol_bal,revol_util,total_acc,collections_12_mths_ex_med,mths_since_last_major_derog,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,36months,60months
count,212999.000000,2.129990e+05,212999.000000,212999.000000,212999.000000,109628.000000,212999.000000,212999.000000,2.129990e+05,212917.000000,212999.000000,212999.000000,62365.000000,212999.000000,212999.000000,2.129990e+05,2.129990e+05,511.000000,511.000000
mean,15257.965530,7.780071e+04,19.360817,0.347462,0.564801,34.169491,11.974883,0.234372,1.798871e+04,53.343256,25.314612,0.021643,45.468356,0.005718,261.951652,1.416537e+05,3.444425e+04,0.622309,0.377691
std,8611.713377,8.188065e+04,31.925871,0.921209,0.861729,22.031958,5.663604,0.662439,2.459627e+04,23.903506,12.035225,0.161511,22.645675,0.081045,2215.188372,1.568766e+05,3.531827e+04,0.485285,0.485285
min,1000.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000e+00,0.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000
25%,8500.000000,4.700000e+04,12.660000,0.000000,0.000000,15.000000,8.000000,0.000000,6.545000e+03,35.500000,17.000000,0.000000,28.000000,0.000000,0.000000,3.143300e+04,1.460000e+04,0.000000,0.000000
50%,14000.000000,6.500000e+04,18.720000,0.000000,0.000000,31.000000,11.000000,0.000000,1.205900e+04,53.500000,24.000000,0.000000,45.000000,0.000000,0.000000,8.138600e+04,2.510000e+04,1.000000,0.000000
75%,20000.000000,9.250000e+04,25.520000,0.000000,1.000000,50.000000,15.000000,0.000000,2.158800e+04,71.700000,32.000000,0.000000,63.000000,0.000000,0.000000,2.097080e+05,4.260000e+04,1.000000,1.000000
max,35000.000000,9.000000e+06,9999.000000,30.000000,5.000000,171.000000,82.000000,86.000000,1.630818e+06,193.000000,169.000000,7.000000,171.000000,5.000000,380757.000000,4.127799e+06,1.641300e+06,1.000000,1.000000

In [113]:
df['term'] = df['term'].astype(str).str.extract('(\d+)').astype(float)

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
/var/folders/21/dr4mf3_126g61t2spl4pgs980000gn/T/ipykernel_22073/2962942547.py:1: SyntaxWarning: invalid escape sequence '\d'
  df['term'] = df['term'].astype(str).str.extract('(\d+)').astype(float)

In [114]:
def clean_emp_length(x):
    if pd.isna(x): return 0
    x = str(x)
    if '<' in x: return 0
    if '+' in x: return 10
    # extract digits
    digits = ''.join(filter(str.isdigit, x))
    return int(digits) if digits else 0

if 'emp_length' in df.columns:
    df['emp_length'] = df['emp_length'].apply(clean_emp_length)

In [115]:
df['earliest_cr_line'] = pd.to_datetime(df['earliest_cr_line'], format='%b-%y', errors='coerce')
# Use 2025 as current reference year
df['credit_history_years'] = 2025 - df['earliest_cr_line'].dt.year
# Fill missing dates with median (rare case)
df['credit_history_years'] = df['credit_history_years'].fillna(df['credit_history_years'].median())
# Drop original
df = df.drop(columns=['earliest_cr_line'])

In [116]:
df['has_delinq_history'] = np.where(df['mths_since_last_delinq'].isnull(), 0, 1)
# Step D2: Fill with 1000 (representing "Infinity" / Never)
df['mths_since_last_delinq'] = df['mths_since_last_delinq'].fillna(1000)

In [117]:
df['mths_since_last_major_derog'] = df['mths_since_last_major_derog'].fillna(1000)

In [118]:
df.head()

,loan_amnt,term,sub_grade,emp_length,home_ownership,annual_inc,verification_status,purpose,dti,delinq_2yrs,...,total_acc,initial_list_status,collections_12_mths_ex_med,mths_since_last_major_derog,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,credit_history_years,has_delinq_history
0,20000,36.0,C1,1,OWN,65000.0,Source Verified,debt_consolidation,20.72,0,...,42,w,0,1000.0,0,0,52303,41000,25.0,0
1,11000,36.0,C2,7,MORTGAGE,40000.0,Source Verified,debt_consolidation,24.57,0,...,41,w,0,79.0,0,332,175731,13100,30.0,1
2,7000,36.0,B3,6,MORTGAGE,32000.0,Source Verified,debt_consolidation,32.41,0,...,36,f,0,1000.0,0,0,202012,16300,30.0,0
3,10000,36.0,B4,10,MORTGAGE,48000.0,Source Verified,credit_card,30.98,0,...,41,f,0,1000.0,0,0,108235,34750,26.0,0
4,9550,36.0,E4,0,RENT,32376.0,Verified,debt_consolidation,32.54,0,...,26,w,0,69.0,0,0,45492,14100,26.0,1

In [119]:
df.describe()

,loan_amnt,term,emp_length,annual_inc,dti,delinq_2yrs,inq_last_6mths,mths_since_last_delinq,open_acc,pub_rec,...,revol_util,total_acc,collections_12_mths_ex_med,mths_since_last_major_derog,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,credit_history_years,has_delinq_history
count,212999.000000,212999.00000,212999.000000,2.129990e+05,212999.000000,212999.000000,212999.000000,212999.000000,212999.000000,212999.000000,...,212917.000000,212999.000000,212999.000000,212999.000000,212999.000000,212999.000000,2.129990e+05,2.129990e+05,212999.000000,212999.000000
mean,15257.965530,43.88353,5.666308,7.780071e+04,19.360817,0.347462,0.564801,502.898760,11.974883,0.234372,...,53.343256,25.314612,0.021643,720.518096,0.005718,261.951652,1.416537e+05,3.444425e+04,30.733403,0.514688
std,8611.713377,11.27188,3.881416,8.188065e+04,31.925871,0.921209,0.861729,482.966693,5.663604,0.662439,...,23.903506,12.035225,0.161511,434.528737,0.081045,2215.188372,1.568766e+05,3.531827e+04,5.935719,0.499785
min,1000.000000,36.00000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,...,0.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,-43.000000,0.000000
25%,8500.000000,36.00000,2.000000,4.700000e+04,12.660000,0.000000,0.000000,30.000000,8.000000,0.000000,...,35.500000,17.000000,0.000000,70.000000,0.000000,0.000000,3.143300e+04,1.460000e+04,29.000000,0.000000
50%,14000.000000,36.00000,6.000000,6.500000e+04,18.720000,0.000000,0.000000,77.000000,11.000000,0.000000,...,53.500000,24.000000,0.000000,1000.000000,0.000000,0.000000,8.138600e+04,2.510000e+04,30.000000,1.000000
75%,20000.000000,60.00000,10.000000,9.250000e+04,25.520000,0.000000,1.000000,1000.000000,15.000000,0.000000,...,71.700000,32.000000,0.000000,1000.000000,0.000000,0.000000,2.097080e+05,4.260000e+04,31.000000,1.000000
max,35000.000000,60.00000,10.000000,9.000000e+06,9999.000000,30.000000,5.000000,1000.000000,82.000000,86.000000,...,193.000000,169.000000,7.000000,1000.000000,5.000000,380757.000000,4.127799e+06,1.641300e+06,56.000000,1.000000

## 4.

In [81]:
get_loan = ['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2']  # with this subgrade they get loan
df['target'] = df['sub_grade'].isin(get_loan).astype(int)  # 0 dont get loan, 1 get loan
df.drop(columns=['sub_grade'], inplace=True)

In [82]:
df.describe()

,loan_amnt,annual_inc,dti,delinq_2yrs,inq_last_6mths,mths_since_last_delinq,open_acc,pub_rec,revol_bal,revol_util,total_acc,collections_12_mths_ex_med,mths_since_last_major_derog,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,has_delinq_history,target
count,212999.000000,2.129990e+05,212999.000000,212999.000000,212999.000000,212999.000000,212999.000000,212999.000000,2.129990e+05,212917.000000,212999.000000,212999.000000,212999.000000,212999.000000,212999.000000,2.129990e+05,2.129990e+05,212999.000000,212999.000000
mean,15257.965530,7.780071e+04,19.360817,0.347462,0.564801,502.898760,11.974883,0.234372,1.798871e+04,53.343256,25.314612,0.021643,720.518096,0.005718,261.951652,1.416537e+05,3.444425e+04,0.514688,0.287748
std,8611.713377,8.188065e+04,31.925871,0.921209,0.861729,482.966693,5.663604,0.662439,2.459627e+04,23.903506,12.035225,0.161511,434.528737,0.081045,2215.188372,1.568766e+05,3.531827e+04,0.499785,0.452714
min,1000.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000e+00,0.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000
25%,8500.000000,4.700000e+04,12.660000,0.000000,0.000000,30.000000,8.000000,0.000000,6.545000e+03,35.500000,17.000000,0.000000,70.000000,0.000000,0.000000,3.143300e+04,1.460000e+04,0.000000,0.000000
50%,14000.000000,6.500000e+04,18.720000,0.000000,0.000000,77.000000,11.000000,0.000000,1.205900e+04,53.500000,24.000000,0.000000,1000.000000,0.000000,0.000000,8.138600e+04,2.510000e+04,1.000000,0.000000
75%,20000.000000,9.250000e+04,25.520000,0.000000,1.000000,1000.000000,15.000000,0.000000,2.158800e+04,71.700000,32.000000,0.000000,1000.000000,0.000000,0.000000,2.097080e+05,4.260000e+04,1.000000,1.000000
max,35000.000000,9.000000e+06,9999.000000,30.000000,5.000000,1000.000000,82.000000,86.000000,1.630818e+06,193.000000,169.000000,7.000000,1000.000000,5.000000,380757.000000,4.127799e+06,1.641300e+06,1.000000,1.000000